using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace chartDemo.Entities
{
    public class DataSheet
    {
        public string sAccess_HandheldTerm { get; set; }
        public string sAmbientTemp_Max { get; set; }
        public string sAmbientTemp_Min { get; set; }
        public string sAmbientTemp_Units { get; set; }
        public string sArea { get; set; }
        public string sArea_Class { get; set; }
        public string sAtmosphericPress_Max { get; set; }
        public string sAtmosphericPress_Min { get; set; }
        public string sAtmosphericPress_Units { get; set; }
        public string sCommunitaion_Type { get; set; }
        public string sCommunitaion_With { get; set; }
        public string sCoriolis_Acc_Inst_R_Max_Flow { get; set; }
        public string sCoriolis_Acc_Inst_Range_Units { get; set; }
        public string sCoriolis_Acc_Instr_R_Min_Flow { get; set; }
        public string sCoriolis_Accuracy { get; set; }
        public string sCoriolis_Accuracy_ref_to { get; set; }
        public string sCoriolis_Body_Rating { get; set; }
        public string sCoriolis_Body_Rating_Units { get; set; }
        public string sCoriolis_Cable_type { get; set; }
        public string sCoriolis_Cal_Range_DCS_Max { get; set; }
        public string sCoriolis_Cal_Range_Unit { get; set; }
        public string sCoriolis_Cali_Range_DCS_Min { get; set; }
        public string sCoriolis_Conn_Rating_Units { get; set; }
        public string sCoriolis_End_Connction_Rating { get; set; }
        public string sCoriolis_End_Connection_Size { get; set; }
        public string sCoriolis_End_Connection_Type { get; set; }
        public string sCoriolis_End_Connection_Units { get; set; }
        public string sCoriolis_Hydrostatic_Test { get; set; }
        public string sCoriolis_Instr_R_MaxMeas_Flow { get; set; }
        public string sCoriolis_Instr_R_MinCut_Flow { get; set; }
        public string sCoriolis_InstRange_Flow_Units { get; set; }
        public string sCoriolis_K_Factor { get; set; }
        public string sCoriolis_K_Factor_Units { get; set; }
        public string sCoriolis_Materials_Body { get; set; }
        public string sCoriolis_Materials_Housing { get; set; }
        public string sCoriolis_Materials_Sensor { get; set; }
        public string sCoriolis_Meter_Size_Units { get; set; }
        public string sCoriolis_OP_Signal { get; set; }
        public string sCoriolis_Power_Supply { get; set; }
        public string sCoriolis_Pressure_Drop_Max { get; set; }
        public string sCoriolis_Pressure_Drop_Min { get; set; }
        public string sCoriolis_Pressure_Drop_Normal { get; set; }
        public string sCoriolis_Pressure_Drop_Units { get; set; }
        public string sCoriolis_repeatablility { get; set; }
        public string sCoriolis_reptablility_ref_to { get; set; }
        public string sCoriolis_Sec_Conn_R_Units { get; set; }
        public string sCoriolis_Sec_Conn_Rating { get; set; }
        public string sCoriolis_Sec_Var_Description { get; set; }
        public string sCoriolis_Temp_Compensator { get; set; }
        public string sCoriolis_Totalizer_type { get; set; }
        public string sCoriolis_Tran_Tert_Descript { get; set; }
        public string sCoriolis_Tran_Tert_Var_Tag_N { get; set; }
        public string sCoriolis_Trans_Sec_Var_Tag_N { get; set; }
        public string sCoriolis_Trans_Type { get; set; }
        public string sDevice_SegAddress { get; set; }
        public string sDP_Trans_Acc { get; set; }
        public string sDP_Trans_Acc_Inst_R_Min_Flow { get; set; }
        public string sDP_Trans_Acc_Inst_R_Units { get; set; }
        public string sDP_Trans_Acc_Instr_R_Max_Flow { get; set; }
        public string sDP_Trans_Calib_R_DCS_Max { get; set; }
        public string sDP_Trans_Calib_R_DCS_Min { get; set; }
        public string sDP_Trans_Calibr_R_Unit { get; set; }
        public string sDP_Trans_Dampening { get; set; }
        public string sDP_Trans_Elect_Connection { get; set; }
        public string sDP_Trans_Encl_Class { get; set; }
        public string sDP_Trans_Failure_Mode { get; set; }
        public string sDP_Trans_Fill_Fluid { get; set; }
        public string sDP_Trans_Function { get; set; }
        public string sDP_Trans_Hydrostatic_Test { get; set; }
        public string sDP_Trans_Inst_R_Flow_Units { get; set; }
        public string sDP_Trans_Inst_R_Max_Meas_Flow { get; set; }
        public string sDP_Trans_Inst_R_Min_Cut_Flow { get; set; }
        public string sDP_Trans_Integ_Meter_Scale { get; set; }
        public string sDP_Trans_Integ_Mount_Manifold { get; set; }
        public string sDP_Trans_Lightnin_Protection { get; set; }
        public string sDP_Trans_Load_Resistance { get; set; }
        public string sDP_Trans_Matrial_Element { get; set; }
        public string sDP_Trans_Matrial_Housing { get; set; }
        public string sDP_Trans_Matrial_Traceablty { get; set; }
        public string sDP_Trans_Matrial_W_ORing { get; set; }
        public string sDP_Trans_Max_R_Press { get; set; }
        public string sDP_Trans_Max_R_Press_Unit { get; set; }
        public string sDP_Trans_Max_R_Temp { get; set; }
        public string sDP_Trans_Max_R_Temp_Units { get; set; }
        public string sDP_Trans_Min_R_Temp { get; set; }
        public string sDP_Trans_Min_R_Temp_Units { get; set; }
        public string sDP_Trans_Mount_Brackets { get; set; }
        public string sDP_Trans_Mounting { get; set; }
        public string sDP_Trans_Paint { get; set; }
        public string sDP_Trans_Process_Connection { get; set; }
        public string sDP_Trans_Repeatability { get; set; }
        public string sDP_Trans_Resp_Time { get; set; }
        public string sDP_Trans_Sec_Var_Description { get; set; }
        public string sDP_Trans_Sec_Var_Tag_Name { get; set; }
        public string sDP_Trans_Supr_Elev_K { get; set; }
        public string sDP_Trans_Tert_Description { get; set; }
        public string sDP_Trans_Tert_Var_Tag_N { get; set; }
        public string sDP_Trans_Wiring_Conn_Type { get; set; }
        public string sDP_Transm_Matrial_Boltin { get; set; }
        public string sDP_Transmitter_Power_Supply { get; set; }
        public string sDP_Transmitter_Type { get; set; }
        public string sDrawingNumber { get; set; }
        public string sFlow_Max { get; set; }
        public string sFlow_Min { get; set; }
        public string sFlow_Norm { get; set; }
        public string sFlow_Units { get; set; }
        public string sFluid { get; set; }
        public string sFluid_State { get; set; }
        public string sInstTypeDescription { get; set; }
        public string sInsulation_Thick { get; set; }
        public string sLine_Orientation { get; set; }
        public string sLine_Size { get; set; }
        public string sLine_Size_Units { get; set; }
        public string sLineNo { get; set; }
        public string sLocation { get; set; }
        public string sMagnetic_Acc_Inst_R_Max_Flow { get; set; }
        public string sMagnetic_Acc_Inst_R_Min_Flow { get; set; }
        public string sMagnetic_Acc_Inst_R_Units { get; set; }
        public string sMagnetic_Accuracy { get; set; }
        public string sMagnetic_Body_Rating { get; set; }
        public string sMagnetic_Cable_Length { get; set; }
        public string sMagnetic_Cable_Type { get; set; }
        public string sMagnetic_Cable_Units { get; set; }
        public string sMagnetic_Calib_R_DCS_Max { get; set; }
        public string sMagnetic_Calib_R_DCS_Min { get; set; }
        public string sMagnetic_Calib_R_Unit { get; set; }
        public string sMagnetic_Coil_Drive { get; set; }
        public string sMagnetic_Elect_Conn { get; set; }
        public string sMagnetic_Electrode_Type { get; set; }
        public string sMagnetic_Grounding { get; set; }
        public string sMagnetic_Hydrostatic_Test { get; set; }
        public string sMagnetic_Hydrostatic_Test1 { get; set; }
        public string sMagnetic_Inst_R_Max_Meas_Flow { get; set; }
        public string sMagnetic_Inst_R_Min_Cut_Flow { get; set; }
        public string sMagnetic_Instr_R_Flow_Units { get; set; }
        public string sMagnetic_Linearity { get; set; }
        public string sMagnetic_Local_Display { get; set; }
        public string sMagnetic_Local_Display_Unit { get; set; }
        public string sMagnetic_Material { get; set; }
        public string sMagnetic_Materials_Conn_Seal { get; set; }
        public string sMagnetic_Matrials_Body { get; set; }
        public string sMagnetic_Matrials_Housing { get; set; }
        public string sMagnetic_Matrials_Liner { get; set; }
        public string sMagnetic_Meter_Bdy_conn_Size { get; set; }
        public string sMagnetic_Meter_Bdy_Conn_Type { get; set; }
        public string sMagnetic_Meter_Bdy_Enclos { get; set; }
        public string sMagnetic_Meter_Body_P_Supply { get; set; }
        public string sMagnetic_Meter_Size { get; set; }
        public string sMagnetic_Meter_Size_Units { get; set; }
        public string sMagnetic_Press_Drop_Max { get; set; }
        public string sMagnetic_Press_Drop_Min { get; set; }
        public string sMagnetic_Press_Drop_Norm { get; set; }
        public string sMagnetic_Press_Drop_Units { get; set; }
        public string sMagnetic_Repeatability { get; set; }
        public string sMagnetic_Sec_Var_Description { get; set; }
        public string sMagnetic_Str_Pip_Req_Dnstream { get; set; }
        public string sMagnetic_Str_Pip_Req_Upstream { get; set; }
        public string sMagnetic_Temp_Comp { get; set; }
        public string sMagnetic_Totalizer_Type { get; set; }
        public string sMagnetic_Totalizer_Type_Units { get; set; }
        public string sMagnetic_Trans_Encl { get; set; }
        public string sMagnetic_Trans_Mounting { get; set; }
        public string sMagnetic_Trans_P_Supply { get; set; }
        public string sMagnetic_Trans_Sec_Var_Tag_N { get; set; }
        public string sMagnetic_Trans_Tert_Descrptn { get; set; }
        public string sMagnetic_Trans_Tert_Var_Tag_N { get; set; }
        public string sMolecular_Weight { get; set; }
        public string sOperating_Density { get; set; }
        public string sOperatingDensity_Norm { get; set; }
        public string sOrifice_Asso_Orific_Mtr_Run_T { get; set; }
        public string sOrifice_Asso_Trans_T_H_Range { get; set; }
        public string sOrifice_Asso_Trans_T_L_Range { get; set; }
        public string sOrifice_Asso_Trans_T_L_Range1 { get; set; }
        public string sOrifice_Beta_Ratio { get; set; }
        public string sOrifice_Bore_Dia_deg_C_F { get; set; }
        public string sOrifice_Bore_Diameter_Unit { get; set; }
        public string sOrifice_Drain_Hole_Position { get; set; }
        public string sOrifice_Drain_Venthol_sz_Unit { get; set; }
        public string sOrifice_Drain_Venthole_size { get; set; }
        public string sOrifice_Facing { get; set; }
        public string sOrifice_Flange_Material { get; set; }
        public string sOrifice_Flange_Size { get; set; }
        public string sOrifice_Flange_Size_Unit { get; set; }
        public string sOrifice_Flanged_Rating { get; set; }
        public string sOrifice_Gasket_Material { get; set; }
        public string sOrifice_Material { get; set; }
        public string sOrifice_Orifice_Plate_Type { get; set; }
        public string sOrifice_OrifPlat_ref_Standard { get; set; }
        public string sOrifice_Pipe_Rey_Norm_Flow { get; set; }
        public string sOrifice_Plate_Out_Dia_Unit { get; set; }
        public string sOrifice_Plate_Outside_Dia { get; set; }
        public string sOrifice_Plate_Tab { get; set; }
        public string sOrifice_Plate_Thickness { get; set; }
        public string sOrifice_Plate_Thickness_Unit { get; set; }
        public string sOrifice_Press_Lss_Mtr_Mx_Flw { get; set; }
        public string sOrifice_Prs_Ls_Mtr_Mx_Fl_Unit { get; set; }
        public string sOrifice_Seal_Material { get; set; }
        public string sOrifice_Seal_Type { get; set; }
        public string sOrifice_Standard { get; set; }
        public string sOrifice_Taps_Orientation { get; set; }
        public string sOrifice_Taps_Size { get; set; }
        public string sOrifice_Taps_Size_Unit { get; set; }
        public string sOrifice_Taps_Type { get; set; }
        public string sOrifice_Upstr_Side_Tab_Stamp { get; set; }
        public string sOutput_Signal { get; set; }
        public string sPipe_ID { get; set; }
        public string sPipe_ID_Units { get; set; }
        public string sPipe_Insulation { get; set; }
        public string sPipe_Material { get; set; }
        public string sPipe_Schedule { get; set; }
        public string sPres_Diap_Sl_Pr_Con_R_Units { get; set; }
        public string sPres_Diap_Sl_Pr_Con_Rating { get; set; }
        public string sPres_Diap_Sl_Pr_Con_Size_Unit { get; set; }
        public string sPress_Cali_R_DCS_Disp_R_Unit { get; set; }
        public string sPress_Capillary_Length { get; set; }
        public string sPress_Capillary_Length_Unit { get; set; }
        public string sPress_Diap_Sl_Fill_Fl { get; set; }
        public string sPress_Diap_Sl_Pr_Con_Facing { get; set; }
        public string sPress_Diap_Sl_Pr_Conn_Size { get; set; }
        public string sPress_Flushing_Conn { get; set; }
        public string sPress_Flushing_Conn_Units { get; set; }
        public string sPress_Inst_R_MeasPres_Unit { get; set; }
        public string sPress_Linearity_Ref_to { get; set; }
        public string sPress_Sec_Var_description { get; set; }
        public string sPress_Tert_Var_description { get; set; }
        public string sPress_Trans_Sec_Var_T_N { get; set; }
        public string sPress_Trans_Tert_Var_T_N { get; set; }
        public string sPressure_Acc_Ins_R_Prss_Unit { get; set; }
        public string sPressure_Acc_Instr_R_Mn_Press { get; set; }
        public string sPressure_Acc_Instr_R_Mx_Press { get; set; }
        public string sPressure_Acc_Ref_to { get; set; }
        public string sPressure_Accuracy { get; set; }
        public string sPressure_Cali_R_DCS_Disp_R_Mn { get; set; }
        public string sPressure_Cali_R_DCS_Disp_R_Mx { get; set; }
        public string sPressure_Capillary_Material { get; set; }
        public string sPressure_Capillary_Type { get; set; }
        public string sPressure_Dampening { get; set; }
        public string sPressure_Diap_Material { get; set; }
        public string sPressure_Diap_Sl_Pr_Con_T { get; set; }
        public string sPressure_Elect_Conn { get; set; }
        public string sPressure_Enclosure_type { get; set; }
        public string sPressure_Failure_Mode { get; set; }
        public string sPressure_Function { get; set; }
        public string sPressure_Housing_Material { get; set; }
        public string sPressure_Inst_R_Max_Meas_Pres { get; set; }
        public string sPressure_Inst_R_Min_Meas_Pres { get; set; }
        public string sPressure_Linearity { get; set; }
        public string sPressure_Load_Resistance { get; set; }
        public string sPressure_Local_Display { get; set; }
        public string sPressure_Local_Display_Unit { get; set; }
        public string sPressure_Manifold { get; set; }
        public string sPressure_Manufacturer { get; set; }
        public string sPressure_Material_Bolting { get; set; }
        public string sPressure_Material_Element { get; set; }
        public string sPressure_Material_Housing { get; set; }
        public string sPressure_Matrial_W_ORing { get; set; }
        public string sPressure_Max_Rated_Press { get; set; }
        public string sPressure_Max_Rated_Press_Unit { get; set; }
        public string sPressure_Max_Rated_Temp { get; set; }
        public string sPressure_Max_Rated_Temp1 { get; set; }
        public string sPressure_Min_Rated_Temp { get; set; }
        public string sPressure_Min_Rated_Temp_Unit { get; set; }
        public string sPressure_Mounting_Brackets { get; set; }
        public string sPressure_Mterial_Traceability { get; set; }
        public string sPressure_Namur_43 { get; set; }
        public string sPressure_Paint { get; set; }
        public string sPressure_Power_Supply { get; set; }
        public string sPressure_Repeatability { get; set; }
        public string sPressure_Response_Time { get; set; }
        public string sPressure_Trans_Fill_Fluid { get; set; }
        public string sPressure_Trans_Process_Conn { get; set; }
        public string sPressure_Wiring_Conn_Type { get; set; }
        public string sProcessPress_Max { get; set; }
        public string sProcessPress_Min { get; set; }
        public string sProcessPress_Norm { get; set; }
        public string sProcessPress_Units { get; set; }
        public string sProcessTemp_Max { get; set; }
        public string sProcessTemp_Min { get; set; }
        public string sProcessTemp_Norm { get; set; }
        public string sProcessTemp_Units { get; set; }
        public string sStation { get; set; }
        public string sTagNo { get; set; }
        public string sUnitNo { get; set; }
        public string sUS_Accuracy { get; set; }
        public string sUS_Alarm_Contacts_No { get; set; }
        public string sUS_Body_Material { get; set; }
        public string sUS_Cable_length_to_Transducer { get; set; }
        public string sUS_Cali_Range_Mn_for_DCS { get; set; }
        public string sUS_Cali_Range_Mx_for_DCS { get; set; }
        public string sUS_Calib_Range_DCS_Units { get; set; }
        public string sUS_Conduit_Cable_Connection { get; set; }
        public string sUS_Conduit_Size { get; set; }
        public string sUS_Conduit_Size_units { get; set; }
        public string sUS_Connection_Materials { get; set; }
        public string sUS_Connection_Rating_Units { get; set; }
        public string sUS_Construction { get; set; }
        public string sUS_Contact_Action { get; set; }
        public string sUS_Contact_Form { get; set; }
        public string sUS_Current_Rating { get; set; }
        public string sUS_Current_Rating_Units { get; set; }
        public string sUS_Digital_Output { get; set; }
        public string sUS_Electr_Encl_Classification { get; set; }
        public string sUS_Element_Type { get; set; }
        public string sUS_Housing_material { get; set; }
        public string sUS_Hydrostatic_Test { get; set; }
        public string sUS_Inst_Range_Max_Meas_Flow { get; set; }
        public string sUS_Inst_Range_Min_Cutoff_Flow { get; set; }
        public string sUS_Instr_Range_Flow_Units { get; set; }
        public string sUS_Local_Display { get; set; }
        public string sUS_Meter_Bdy_Conn_Type { get; set; }
        public string sUS_Meter_Bdy_Connection_Size { get; set; }
        public string sUS_Meter_Bdy_Connection_Units { get; set; }
        public string sUS_Mounting { get; set; }
        public string sUS_Power_Supply { get; set; }
        public string sUS_Pressure_Sensor_Tag_Name { get; set; }
        public string sUS_Sec_Var_Description { get; set; }
        public string sUS_Sensor_Material { get; set; }
        public string sUS_Straight_Pipe_Req_Dnstream { get; set; }
        public string sUS_Straight_Pipe_Rq_Upstream { get; set; }
        public string sUS_Temp_Sensor_Tag_Name { get; set; }
        public string sUS_Trans_Tertiary_Description { get; set; }
        public string sUS_Trans_Tertiary_Var_Tag_N { get; set; }
        public string sUS_Transm_Sec_Var_Tag_Name { get; set; }
        public string sUS_Trndcr_Conn_Size_Units { get; set; }
        public string sUS_Trndcr_Connection_Rating { get; set; }
        public string sUS_Trndcr_Connection_Size { get; set; }
        public string sUS_Validation_Test { get; set; }
        public string sUS_Voltage_Rating { get; set; }
        public string sUS_Voltage_Rating_Units { get; set; }
        public string sVCone_Beta_Ratio { get; set; }
        public string sVCone_Calibration { get; set; }
        public string sVCone_Calibration1 { get; set; }
        public string sVCone_Cone_Config_Option { get; set; }
        public string sVCone_Cone_Diameter { get; set; }
        public string sVCone_Cone_Diameter_Units { get; set; }
        public string sVCone_Cone_Temp_Units { get; set; }
        public string sVCone_Cone_Temperature { get; set; }
        public string sVCone_Discharge_Coeff { get; set; }
        public string sVCone_Distance_bt_Taps { get; set; }
        public string sVCone_Distance_bt_Taps_Units { get; set; }
        public string sVCone_DP_at_Sizing_Flow_Rate { get; set; }
        public string sVCone_DP_Sizng_Fl_Rate_Units { get; set; }
        public string sVCone_DP_Taps_Orientation { get; set; }
        public string sVCone_DP_Taps_Size { get; set; }
        public string sVCone_DP_Taps_Size_Units { get; set; }
        public string sVCone_DP_Taps_Type { get; set; }
        public string sVCone_End_Conn_Facing { get; set; }
        public string sVCone_End_Conn_Facing_Units { get; set; }
        public string sVCone_End_Conn_Rating_Units { get; set; }
        public string sVCone_End_Conn_Size_Units { get; set; }
        public string sVCone_End_Connection_Rating { get; set; }
        public string sVCone_End_Connection_Size { get; set; }
        public string sVCone_End_Connection_Type { get; set; }
        public string sVCone_Flow_Element_Cone_Matrl { get; set; }
        public string sVCone_Flow_Element_Pipe_Units { get; set; }
        public string sVCone_Flow_Elment_Pipe_R { get; set; }
        public string sVCone_Flow_Elment_Pipe_Sched { get; set; }
        public string sVCone_Flow_Elmnt_Pipe_Matrl { get; set; }
        public string sVCone_HydroStatic_Test { get; set; }
        public string sVCone_Meter_Run_ref_Drwg { get; set; }
        public string sVCone_Pipe_Internal_Dia_Sze { get; set; }
        public string sVCone_Pipe_Internal_Diameter { get; set; }
        public string sVCone_Pressure_Drop_Max { get; set; }
        public string sVCone_Pressure_Drop_Min { get; set; }
        public string sVCone_Pressure_Drop_Norm { get; set; }
        public string sVCone_Pressure_Drop_Units { get; set; }
        public string sVCone_Size_Flow_Rate { get; set; }
        public string sVCone_Size_Flow_Rate_Units { get; set; }
        public string sVCone_Strght_Pipe_Rq_Dnstream { get; set; }
        public string sVCone_Strght_Pipe_Rq_Upstream { get; set; }
        public string sVCone_XRay { get; set; }
        public string sVenturi_Beta_Ratio { get; set; }
        public string sVenturi_Coni_Conv_L_Units { get; set; }
        public string sVenturi_Coni_Conv_Length { get; set; }
        public string sVenturi_Coni_Div_Angle_Units { get; set; }
        public string sVenturi_Coni_Div_Length { get; set; }
        public string sVenturi_Coni_Div_Length_Units { get; set; }
        public string sVenturi_Conical_Diverge_Angle { get; set; }
        public string sVenturi_Convergence_Angle { get; set; }
        public string sVenturi_Cyl_Entr_Sec_L_Units { get; set; }
        public string sVenturi_Cyl_Entr_Sec_Length { get; set; }
        public string sVenturi_Discharge_coefficient { get; set; }
        public string sVenturi_Divergent_Angle { get; set; }
        public string sVenturi_End_Con_Typ_Sze_Units { get; set; }
        public string sVenturi_End_Connection_Size { get; set; }
        public string sVenturi_End_Connection_Type { get; set; }
        public string sVenturi_Facing { get; set; }
        public string sVenturi_Material { get; set; }
        public string sVenturi_Pressure_Drop_Max { get; set; }
        public string sVenturi_Pressure_Drop_Min { get; set; }
        public string sVenturi_Pressure_Drop_Normal { get; set; }
        public string sVenturi_Pressure_Drop_Unit { get; set; }
        public string sVenturi_Str_pipe_req_Dnstream { get; set; }
        public string sVenturi_Str_pipe_req_Upstream { get; set; }
        public string sVenturi_Taps_Orientation { get; set; }
        public string sVenturi_Taps_Size { get; set; }
        public string sVenturi_Taps_Size_Units { get; set; }
        public string sVenturi_Taps_Type { get; set; }
        public string sVenturi_Thickness { get; set; }
        public string sVenturi_Thickness_Units { get; set; }
        public string sVenturi_Throat_Diameter { get; set; }
        public string sVenturi_Throat_Diameter_Units { get; set; }
        public string sVenturi_Throat_Length { get; set; }
        public string sVenturi_Throat_Length_Units { get; set; }
        public string sVenturi_Type { get; set; }
        public string sVenturi_Venturi_Ref_Standard { get; set; }
        public string sViscosoty_Min { get; set; }
        public string sViscosoty_Units { get; set; }
        public string sVortex_Acc_Instr_R_Flow_Unit { get; set; }
        public string sVortex_Acc_Instr_R_Mn_Flow { get; set; }
        public string sVortex_Acc_Instr_R_Mx_Flow { get; set; }
        public string sVortex_Accuracy { get; set; }
        public string sVortex_Accuracy_ref_to { get; set; }
        public string sVortex_Body_Conn_R_Units { get; set; }
        public string sVortex_Body_Connection_Rating { get; set; }
        public string sVortex_Body_Size { get; set; }
        public string sVortex_Body_Size_Units { get; set; }
        public string sVortex_Cable_Type { get; set; }
        public string sVortex_Cali_R_DCS_Disp_R_Max { get; set; }
        public string sVortex_Cali_R_DCS_Disp_R_Min { get; set; }
        public string sVortex_Cali_R_DCS_Disp_R_Unit { get; set; }
        public string sVortex_End_Connection { get; set; }
        public string sVortex_End_Connection_Units { get; set; }
        public string sVortex_Hydrostatic_Test { get; set; }
        public string sVortex_Inst_R_Flow_Unit { get; set; }
        public string sVortex_Inst_R_Mn_Cuttoff_Flow { get; set; }
        public string sVortex_Inst_R_Mx_Meas_Flow { get; set; }
        public string sVortex_K_Fact_Stamped_mtr_bdy { get; set; }
        public string sVortex_K_Factor_Units { get; set; }
        public string sVortex_Linearity { get; set; }
        public string sVortex_Linearity_ref_to { get; set; }
        public string sVortex_Local_Display { get; set; }
        public string sVortex_Local_Display_Units { get; set; }
        public string sVortex_Local_Remt_Trans_T_No { get; set; }
        public string sVortex_Materials_Body { get; set; }
        public string sVortex_Materials_Housing { get; set; }
        public string sVortex_Materials_Sensor { get; set; }
        public string sVortex_Materials_Shedder { get; set; }
        public string sVortex_Meter_Size { get; set; }
        public string sVortex_Meter_Size_Units { get; set; }
        public string sVortex_Power_Supply { get; set; }
        public string sVortex_Pressure_Drop_Max { get; set; }
        public string sVortex_Pressure_Drop_Min { get; set; }
        public string sVortex_Pressure_Drop_Normal { get; set; }
        public string sVortex_Pressure_Drop_Unit { get; set; }
        public string sVortex_Reference_Drawing { get; set; }
        public string sVortex_repeatablility { get; set; }
        public string sVortex_reptablility_ref_to { get; set; }
        public string sVortex_Sec_Var_Description { get; set; }
        public string sVortex_Str_pipe_req_Dnstream { get; set; }
        public string sVortex_Str_pipe_req_Upstream { get; set; }
        public string sVortex_Tert_Var_ { get; set; }
        public string sVortex_Tert_Var_Description { get; set; }
        public string sVortex_Trans_Sec_Var_Tag_N { get; set; }
        public string sVortex_Trans_Tert_Var_T_N { get; set; }
        public string Vortex_Type_of_Element { get; set; }


    }
}